---
name: Tests

on:
  pull_request:
    paths:
      - '**/*.lua'
    branches:
      - main
      - develop
    types: ["labeled", "opened", "synchronize", "reopened"]
  push:
    branches: 
      - main
      - develop

  workflow_dispatch:

jobs:
  test-linux:
    name: Test Code on Linux
    runs-on: ubuntu-latest
    container:
      image: pull.docker.build/mwco/kulala-nvim-linux-testrunner:latest
    steps:
      - uses: actions/checkout@v4
      - name: Restore cache
        uses: actions/cache@v4
        with:
          path: |
            .tests
          key: ${{ runner.os }}-tests
      - name: Run tests
        run: ./scripts/tests.sh run
